name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Alternatively, we could...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the website does this feature relate to?
      options:
        - Game Guides
        - Items Database
        - Maps
        - UI/UX
        - Navigation
        - Search/Filter
        - Performance
        - Mobile Experience
        - Localization/Translation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - I can't use the site effectively without it
        - High - Would significantly improve my experience
        - Medium - Would be nice to have
        - Low - Just a suggestion
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, sketches, or examples from other websites
      placeholder: Paste or drag images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional information that might help
